// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['main']['App']['Add'](arg1);
}

export function ChangeDatastorePath(arg1) {
  return window['go']['main']['App']['ChangeDatastorePath'](arg1);
}

export function GetDatastorePath() {
  return window['go']['main']['App']['GetDatastorePath']();
}

export function GetItems() {
  return window['go']['main']['App']['GetItems']();
}

export function LoadDatastore() {
  return window['go']['main']['App']['LoadDatastore']();
}

export function Remove(arg1) {
  return window['go']['main']['App']['Remove'](arg1);
}

export function Reset() {
  return window['go']['main']['App']['Reset']();
}
