// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1:string):Promise<{[key: number]: string}>;

export function ChangeDatastorePath(arg1:string):Promise<string>;

export function GetDatastorePath():Promise<string>;

export function GetItems():Promise<{[key: number]: string}>;

export function LoadDatastore():Promise<void>;

export function Remove(arg1:number):Promise<{[key: number]: string}>;

export function Reset():Promise<{[key: number]: string}>;
