// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['main']['App']['Add'](arg1);
}

export function Remove(arg1) {
  return window['go']['main']['App']['Remove'](arg1);
}

export function Reset() {
  return window['go']['main']['App']['Reset']();
}
